---
# Homepage Bookmarks
# Quick access to useful resources

- Infrastructure Docs:
    - Repository:
        - abbr: GH
          href: https://github.com/yourusername/infrastructure

- Monitoring:
    - Grafana Dashboards:
        - abbr: GF
          href: https://grafana.onurx.com/dashboards
    - Prometheus Targets:
        - abbr: PM
          href: https://prometheus.onurx.com/targets
    - Loki Logs:
        - abbr: LK
          href: https://grafana.onurx.com/explore

- External Services:
    - 1Password:
        - abbr: 1P
          href: https://my.1password.com
    - Cloudflare:
        - abbr: CF
          href: https://dash.cloudflare.com

- Documentation:
    - Docker Hub:
        - abbr: DH
          href: https://hub.docker.com
    - Traefik Docs:
        - abbr: TF
          href: https://doc.traefik.io/traefik/
    - Grafana Docs:
        - abbr: GD
          href: https://grafana.com/docs/
